package operation;

public enum TypeOperation {
	NEW_ACCOUNT,
	OPEN_ACCOUNT,
	CLOSE_ACCOUNT,
	WITHDRAWAL,
	DEPOSIT,
	BUY_FINANCIAL_ITEM,
	SELL_FINANCIAL_ITEM,
	LIST_ACCOUNTS,
	LIST_FINANCIAL_ITEM,
	SHOW_HISTORY,
	TRANSFERT_OPERATION,
	SHOW_BALANCE,
	UNDEFINED
}
